### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Thunder105** [AOSPK/official_devices#103]
## Device you want to apply for
```
violet
```

## Device tree sources

```
https://github.com/Thunder105/android_device_xiaomi_violet
https://github.com/Thunder105/caf_vendor_xiaomi_violet
https://github.com/Thunder105/caf_kernel_xiaomi_violet
```

## Number of ROM's you maintain officially
```
2
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
@Thunder105
```

### GitHub username
```
@Thunder105
```

**Comment by Jorg3Lucas** [comment]
Hello, unfortunately we cannot accept you at the moment as your devices sources violate our CoC
