### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by LmaoDevice** [AOSPK/official_devices#105]
## Device you want to apply for
```
Daisy Xiaomi Mi A2 Lite
```

## Device tree sources

```
https://github.com/LmaoDevice/android_device_xiaomi_daisy/tree/AOSPK
https://github.com/LmaoDevice/kernel_xiaomi_msm8953
https://github.com/LmaoDevice/android_vendor_xiaomi_daisy
```

## Number of ROM's you maintain officially
```
0
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
Lmao_Device
```

### GitHub username

LmaoDevice
```

**Comment by dustxyz** [comment]
Hi, @LmaoDevice, thanks for being interesed for maintain this ROM, for me, you are okay for being accepted to the team, please do a pull request in official devices repo, welcome!.

**Comment by mamutal91** [comment]
That's fine by me, but remember that you need to use the branch and repository names as per our project
