### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by matt0301** [AOSPK/official_devices#112]
## Device you want to apply for
```
hotdogb (Oneplus 7T)
```

## Device tree sources

```
https://github.com/matt0301/android_device_oneplus_hotdogb
https://github.com/matt0301/android_device_oneplus_sm8150-common
https://github.com/matt0301/vendor_oneplus_sm8150-common
https://github.com/matt0301/vendor_oneplus_hotdogb
https://github.com/matt0301/kernel_oneplus_sm8150
https://github.com/matt0301/hardware_oneplus
```

## Number of ROM's you maintain officially
```
2
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
matt0301
```

### GitHub username
```
matt0301
```

**Comment by clawside** [comment]
Good morning / afternoon / evening, I hope you are well, I am glad that you are interested in applying for AOSPK, I just analyzed your trees in detail, and I did not find anything wrong. Welcome to the team, please make a PR to this repo, filling the requested changes for your device.
