### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by SH4ND0W** [AOSPK/official_devices#117]
## Device you want to apply for
```
Beryllium
```

## Device tree sources

```
https://github.com/SH4ND0W/device_xiaomi_beryllium
https://github.com/SH4ND0W/kernel_xiaomi_beryllium
https://github.com/SH4ND0W/vendor_xiaomi_beryllium
https://github.com/SH4ND0W/device_xiaomi_sdm845-common
```

## Number of ROM's you maintain officially
```
0
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
Miqueiasshandow999
```

### GitHub username
```
SH4ND0W
```

**Comment by mamutal91** [comment]
Apparently, from your commit history, you don't know how to use git
