### ISSUE TITLE
New Maintainer 

### ISSUE THREAD

**Issue by jaaat4u** [AOSPK/official_devices#119]
## Device you want to apply for
```
beryllium
```

## Device tree sources

```
https://github.com/jaaat4u/device_xiaomi_beryllium
https://github.com/jaaat4u/NikoKernel-Stock
https://github.com/XtremeOrnob/vendor_xiaomi
https://github.com/jaaat4u/device_xiaomi_sdm845-common
```

## Number of ROM's you maintain officially
```
0
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
<@jaat4u>
```

### GitHub username
```
<jaaat4u>
```

**Comment by mamutal91** [comment]
We currently have no private server for Kraken, if you are able to build it, let me know

**Comment by clawside** [comment]
Hello, hope you're good, thanks for being interesed in applying for Kraken,let's start, your commit history in the common tree is decent, but i found some issues with your commit history in the device tree, first, you're doing 5 innecessary reverts, this can be easily fixed rebasing the tree, second, you must use your own or forked vendor, using another's work is not permited, three, having anykernel in the kernel is totally useless if you don't use any CI. Hope you understand, have a good day.

**Comment by jaaat4u** [comment]
> We currently have no private server for Kraken, if you are able to build it, let me know

yeah i can build on gcp
