### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by thefaizanbashir** [AOSPK/official_devices#124]
## Device you want to apply for
```
sweet
```

## Device tree sources

```
https://github.com/thefaizanbashir/device_xiaomi_sweet/tree/aospk
https://github.com/thefaizanbashir/vendor_xiaomi_sweet
https://github.com/vantoman/kernel_xiaomi_sm6150
```

## Number of ROM's you maintain officially
```
1
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
the_doctorstrange
```

### GitHub username
```
thefaizanbashir
```

**Comment by mamutal91** [comment]
1 - Your bringup is not for our project.
2 - I see you are making repeated commits, and sometimes it could be 2 in 1... do you commit through the browser?

**Comment by thefaizanbashir** [comment]
Kindly check updated links. I've fixed my commit history and did bringup for AOSPK

**Comment by thefaizanbashir** [comment]
You're too late go fuck your rom now
