### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Klozz** [AOSPK/official_devices#94]
## Device you want to apply for
```
Remi Note 9s/ pro /pro max Poco M2 Pro <Miatoll>
```

## Device tree sources

```
https://github.com/Klozz/aospk_device_xiaomi_sm6250-common
https://github.com/Klozz/aospk_device_xiaomi_miatoll
https://github.com/RainbowUnicornXPe/proprietary_xiaomi_sm6250-common
https://github.com/RainbowUnicornXPe/proprietary_xiaomi_miatoll
https://github.com/TheXPerienceProject/android_kernel_xiaomi_sm6250
```

## Number of ROM's you maintain officially
```
1 
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
TeamMEX_XDA
```

### GitHub username
```
klozz
```

**Comment by jeangraff30** [comment]
Good morning, good afternoon and good night

We have analyzed your tree, but unfortunately we cannot accept it for the following reasons:

° We verified that certain commits do not have proper authorship
° We also verified that the tree does not have a proper organization in the commits.

Feel free to open a new issue after solving the reported issues and thank you for your interest in being part of the project
