### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by LmaoDevice** [AOSPK/official_devices#95]
## Device you want to apply for
```
daisy
```

## Device tree sources

```
https://github.com/LmaoDevice/device_xiaomi_daisy
https://github.com/LmaoDevice/vendor_xiaomi_daisy-r
https://github.com/Couchpotato-sauce/kernel_xiaomi_sleepy
```

## Number of ROM's you maintain officially
```
<0>
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
@Lmao_Device
```

### GitHub username
```
LmaoDevice
```

**Comment by jeangraff30** [comment]
Good morning, good afternoon and good night

Thank you for your interest in being part of the team.

Unfortunately we cannot accept it at this time for the following reasons:

° Little knowledge of Android development
° Little knowledge with github CLI

Feel free to write on the project in the future.

**Comment by LmaoDevice** [comment]
Alright maybe next time
