### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by tusharind007** [AOSPK/official_devices#96]
## Device you want to apply for
```
miatoll
```

## Device tree sources

```
https://github.com/tusharind007/device_xiaomi_miatoll
https://github.com/tusharind007/device_xiaomi_sm6250-common
https://github.com/tusharind007/kernel_xiaomi_sm6250
https://github.com/tusharind007/vendor_xiaomi_miatoll
https://github.com/tusharind007/vendor_xiaomi_sm6250-common
```

## Number of ROM's you maintain officially
```
0
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
Tusharind007
```

### GitHub username
```
Tusharind007
```

**Comment by jeangraff30** [comment]
Good morning Good afternoon Good night.

Thank you for your interest in being part of the team, I checked your tree, for me it's all right, to proceed to officialization, you need to remove the FP from the tree, as it is already defined in the frameworks

https://github.com/tusharind007/device_xiaomi_miatoll/blob/5fe9425019d07e7db0709b8e4595a362951eda26/init/init.cpp#L73

**Comment by tusharind007** [comment]
Hi,
required changes has been done and thank you for giving me the opportunity to be part of your team

https://github.com/tusharind007/device_xiaomi_miatoll/commit/577512c8553125b2ec6a932ec6df118df32d9035

**Comment by jeangraff30** [comment]
All very well . now make a PR in that same repository, adding your devices and your information, and send the username you want on the CI, after that we will send your credentials in your telegram
